import type { MockData } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImageUrl = (id: string) => PlaceHolderImages.find(p => p.id === id)?.imageUrl || '';

export const mockData: MockData = {
  users: [
    {
      userId: "user_001",
      email: "priya.sharma@test.com",
      displayName: "Priya Sharma",
      photoURL: getImageUrl("user_priya"),
      location: { city: "Mumbai", state: "Maharashtra", country: "India" },
      bio: "Dog mom to two adorable Golden Retrievers! Love hiking and beach walks with my fur babies 🐕",
      joinedAt: "2024-09-15",
      postCount: 12,
      petCount: 2,
      followers: 145,
      following: 89,
      petIds: ["pet_001", "pet_002"]
    },
    {
      userId: "user_002",
      email: "arjun.patel@test.com",
      displayName: "Arjun Patel",
      photoURL: getImageUrl("user_arjun"),
      location: { city: "Bangalore", state: "Karnataka", country: "India" },
      bio: "Cat dad and software engineer. My cat probably codes better than I do.",
      joinedAt: "2024-10-20",
      postCount: 8,
      petCount: 1,
      followers: 112,
      following: 75,
      petIds: ["pet_003"]
    },
    {
      userId: "user_003",
      email: "ananya.reddy@test.com",
      displayName: "Ananya Reddy",
      photoURL: getImageUrl("user_ananya"),
      location: { city: "Hyderabad", state: "Telangana", country: "India" },
      bio: "Proud parent of an adopted Indie dog. #AdoptDontShop",
      joinedAt: "2023-05-11",
      postCount: 25,
      petCount: 1,
      followers: 320,
      following: 150,
      petIds: ["pet_004"]
    },
     {
      userId: "user_004",
      email: "rohan.mehta@test.com",
      displayName: "Rohan Mehta",
      photoURL: getImageUrl("user_rohan"),
      location: { city: "Delhi", state: "NCR", country: "India" },
      bio: "Beagle owner, which means I'm a professional snack defender.",
      joinedAt: "2024-01-02",
      postCount: 15,
      petCount: 1,
      followers: 98,
      following: 62,
      petIds: ["pet_005"]
    },
    {
      userId: "user_005",
      email: "ishita.gupta@test.com",
      displayName: "Ishita Gupta",
      photoURL: getImageUrl("user_ishita"),
      location: { city: "Pune", state: "Maharashtra", country: "India" },
      bio: "Life is just a series of cat naps and zoomies. Wouldn't have it any other way.",
      joinedAt: "2023-11-18",
      postCount: 18,
      petCount: 3,
      followers: 210,
      following: 110,
      petIds: ["pet_006", "pet_007", "pet_008"]
    },
  ],
  pets: [
    {
      petId: "pet_001",
      ownerId: "user_001",
      ownerName: "Priya Sharma",
      name: "Max",
      type: "Dog",
      breed: "Golden Retriever",
      gender: "Male",
      age: { years: 3, months: 0 },
      birthDate: "2021-06-15",
      color: "Golden",
      weight: 32,
      photo: getImageUrl("pet_max"),
      specialNeeds: "None",
      activityLevel: 8,
      microchipId: "123456789",
      createdAt: "2024-09-15"
    },
    {
      petId: "pet_002",
      ownerId: "user_001",
      ownerName: "Priya Sharma",
      name: "Bella",
      type: "Dog",
      breed: "Golden Retriever",
      gender: "Female",
      age: { years: 2, months: 0 },
      birthDate: "2022-04-01",
      color: "Cream",
      weight: 28,
      photo: getImageUrl("pet_bella"),
      specialNeeds: "None",
      activityLevel: 9,
      microchipId: "987654321",
      createdAt: "2024-09-15"
    },
    {
      petId: "pet_003",
      ownerId: "user_002",
      ownerName: "Arjun Patel",
      name: "Simba",
      type: "Cat",
      breed: "Bengal",
      gender: "Male",
      age: { years: 4, months: 0 },
      birthDate: "2020-08-20",
      color: "Spotted Brown",
      weight: 6,
      photo: getImageUrl("pet_simba"),
      specialNeeds: "None",
      activityLevel: 7,
      microchipId: "112233445",
      createdAt: "2024-10-20"
    },
    {
      petId: "pet_004",
      ownerId: "user_003",
      ownerName: "Ananya Reddy",
      name: "Rocky",
      type: "Dog",
      breed: "Indian Pariah",
      gender: "Male",
      age: { years: 5, months: 0 },
      birthDate: "2019-01-01",
      color: "Brown",
      weight: 20,
      photo: getImageUrl("pet_rocky"),
      specialNeeds: "Rescued",
      activityLevel: 8,
      microchipId: "N/A",
      createdAt: "2023-05-11"
    },
     {
      petId: "pet_005",
      ownerId: "user_004",
      ownerName: "Rohan Mehta",
      name: "Bruno",
      type: "Dog",
      breed: "Beagle",
      gender: "Male",
      age: { years: 2, months: 6 },
      birthDate: "2022-07-10",
      color: "Tricolor",
      weight: 12,
      photo: getImageUrl("pet_bruno"),
      specialNeeds: "Loves food a bit too much.",
      activityLevel: 10,
      microchipId: "556677889",
      createdAt: "2024-01-02"
    }
  ],
  posts: [
    {
      postId: "post_001",
      userId: "user_001",
      userName: "Priya Sharma",
      userPhoto: getImageUrl("user_priya"),
      petId: "pet_001",
      petName: "Max",
      image: getImageUrl("post_juhu"),
      caption: "Morning walks at Juhu Beach with Max and Bella! They absolutely love the sand 🌊 #dogsofinstagram #mumbai",
      likes: 47,
      likedBy: ["user_004", "user_003"],
      comments: [
        { commentId: "cmt_001", userId: "user_004", userName: "Rohan Mehta", userPhoto: getImageUrl("user_rohan"), text: "Such cuties! Bruno would love to meet them 🐕", timestamp: "2025-01-15T08:30:00Z" },
        { commentId: "cmt_002", userId: "user_003", userName: "Ananya Reddy", userPhoto: getImageUrl("user_ananya"), text: "This is pure happiness!", timestamp: "2025-01-15T08:45:00Z" }
      ],
      saved: false,
      createdAt: "2025-01-15T06:00:00Z"
    },
    {
      postId: "post_002",
      userId: "user_002",
      userName: "Arjun Patel",
      userPhoto: getImageUrl("user_arjun"),
      petId: "pet_003",
      petName: "Simba",
      image: getImageUrl("post_simba_code"),
      caption: "Simba judging my code reviews from his favorite perch 😂 #catsofinstagram #coderlife",
      likes: 34,
      likedBy: ["user_005"],
      comments: [
         { commentId: "cmt_003", userId: "user_005", userName: "Ishita Gupta", userPhoto: getImageUrl("user_ishita"), text: "That's the look of a senior developer.", timestamp: "2025-01-15T09:10:00Z" }
      ],
      saved: true,
      createdAt: "2025-01-15T05:00:00Z"
    },
    {
      postId: "post_003",
      userId: "user_003",
      userName: "Ananya Reddy",
      userPhoto: getImageUrl("user_ananya"),
      petId: "pet_004",
      petName: "Rocky",
      image: getImageUrl("post_rocky_rescue"),
      caption: "4 years ago, I found Rocky on the streets. Today, he's my best friend ❤️ #AdoptDontShop #rescuedog",
      likes: 89,
      likedBy: ["user_001", "user_002", "user_004", "user_005"],
      comments: [],
      saved: false,
      createdAt: "2025-01-14T12:00:00Z"
    },
    {
      postId: "post_004",
      userId: "user_004",
      userName: "Rohan Mehta",
      userPhoto: getImageUrl("user_rohan"),
      petId: "pet_005",
      petName: "Bruno",
      image: getImageUrl("post_bruno_paratha"),
      caption: "Bruno stole an entire paratha from the table today. Living up to the Beagle reputation 😂 #beaglelife",
      likes: 56,
      likedBy: ["user_001"],
      comments: [],
      saved: false,
      createdAt: "2025-01-15T03:00:00Z"
    },
    {
      postId: "post_005",
      userId: "user_005",
      userName: "Ishita Gupta",
      userPhoto: getImageUrl("user_ishita"),
      image: getImageUrl("post_bengals_chaos"),
      caption: "Three bengals = chaos multiplied by infinity 😅 #bengalcat #catmom",
      likes: 42,
      likedBy: ["user_002"],
      comments: [],
      saved: false,
      createdAt: "2025-01-15T04:00:00Z"
    }
  ],
  stories: [
    { storyId: "story_001", userId: "user_001", userName: "Priya", userPhoto: getImageUrl("user_priya"), storyImage: getImageUrl("story_max_playing"), timestamp: "2025-01-15T10:00:00Z", expiresAt: "2025-01-16T10:00:00Z" },
    { storyId: "story_002", userId: "user_002", userName: "Arjun", userPhoto: getImageUrl("user_arjun"), storyImage: getImageUrl("story_simba_nap"), timestamp: "2025-01-15T09:00:00Z", expiresAt: "2025-01-16T09:00:00Z" },
    { storyId: "story_003", userId: "user_003", userName: "Ananya", userPhoto: getImageUrl("user_ananya"), storyImage: getImageUrl("story_rocky_park"), timestamp: "2025-01-15T11:00:00Z", expiresAt: "2025-01-16T11:00:00Z" },
    { storyId: "story_004", userId: "user_004", userName: "Rohan", userPhoto: getImageUrl("user_rohan"), storyImage: getImageUrl("story_bruno_zoomies"), timestamp: "2025-01-15T08:00:00Z", expiresAt: "2025-01-16T08:00:00Z" },
    { storyId: "story_005", userId: "user_005", userName: "Ishita", userPhoto: getImageUrl("user_ishita"), storyImage: getImageUrl("story_cats_window"), timestamp: "2025-01-15T12:00:00Z", expiresAt: "2025-01-16T12:00:00Z" },
  ],
  events: [],
  forumTopics: [],
  lostPetAlerts: [],
  tipArticles: [],
  conversations: []
};
