import type { MockData } from './types';
import { PlaceHolderImages } from './placeholder-images';
import { subDays } from 'date-fns';

const getImageUrl = (id: string) => PlaceHolderImages.find(p => p.id === id)?.imageUrl || '';

const now = new Date();

export const mockData: MockData = {
  users: [
    {
      userId: "user_001",
      email: "priya.sharma@test.com",
      displayName: "Priya Sharma",
      photoURL: getImageUrl("user_priya"),
      location: { city: "Mumbai", state: "Maharashtra", country: "India" },
      bio: "Dog mom to two adorable Golden Retrievers! Love hiking and beach walks with my fur babies 🐕",
      joinedAt: "2024-09-15",
      postCount: 12,
      petCount: 2,
      followers: 145,
      following: 89,
      petIds: ["pet_001", "pet_002"]
    },
    {
      userId: "user_002",
      email: "arjun.patel@test.com",
      displayName: "Arjun Patel",
      photoURL: getImageUrl("user_arjun"),
      location: { city: "Bangalore", state: "Karnataka", country: "India" },
      bio: "Cat dad and software engineer. My cat probably codes better than I do.",
      joinedAt: "2024-10-20",
      postCount: 8,
      petCount: 1,
      followers: 112,
      following: 75,
      petIds: ["pet_003"]
    },
    {
      userId: "user_003",
      email: "ananya.reddy@test.com",
      displayName: "Ananya Reddy",
      photoURL: getImageUrl("user_ananya"),
      location: { city: "Hyderabad", state: "Telangana", country: "India" },
      bio: "Proud parent of an adopted Indie dog. #AdoptDontShop",
      joinedAt: "2023-05-11",
      postCount: 25,
      petCount: 1,
      followers: 320,
      following: 150,
      petIds: ["pet_004"]
    },
     {
      userId: "user_004",
      email: "rohan.mehta@test.com",
      displayName: "Rohan Mehta",
      photoURL: getImageUrl("user_rohan"),
      location: { city: "Delhi", state: "NCR", country: "India" },
      bio: "Beagle owner, which means I'm a professional snack defender.",
      joinedAt: "2024-01-02",
      postCount: 15,
      petCount: 1,
      followers: 98,
      following: 62,
      petIds: ["pet_005"]
    },
    {
      userId: "user_005",
      email: "ishita.gupta@test.com",
      displayName: "Ishita Gupta",
      photoURL: getImageUrl("user_ishita"),
      location: { city: "Pune", state: "Maharashtra", country: "India" },
      bio: "Life is just a series of cat naps and zoomies. Wouldn't have it any other way.",
      joinedAt: "2023-11-18",
      postCount: 18,
      petCount: 3,
      followers: 210,
      following: 110,
      petIds: ["pet_006", "pet_007", "pet_008"]
    },
    {
      userId: "user_006",
      email: "shreyan.bagchi@test.com",
      password: "Test@123",
      displayName: "Shreyan Bagchi",
      photoURL: getImageUrl("user_shreyan"),
      location: { city: "Bangalore", state: "Karnataka", country: "India" },
      bio: "Just a guy and his dog, exploring the Garden City.",
      joinedAt: "2024-08-01",
      postCount: 5,
      petCount: 1,
      followers: 50,
      following: 20,
      petIds: ["pet_009"]
    },
    {
      userId: "user_007",
      email: "ishaan.singh@test.com",
      password: "Test@123",
      displayName: "Ishaan Som Singh",
      photoURL: getImageUrl("user_ishaan"),
      location: { city: "Bangalore", state: "Karnataka", country: "India" },
      bio: "Persian cat enthusiast. My camera roll is 99% cat photos.",
      joinedAt: "2024-07-22",
      postCount: 8,
      petCount: 1,
      followers: 78,
      following: 45,
      petIds: ["pet_010"]
    },
    {
      userId: "user_008",
      email: "grad.circle@test.com",
      password: "Test@123",
      displayName: "Grad Circle",
      photoURL: getImageUrl("user_grad_circle"),
      location: { city: "Bangalore", state: "Karnataka", country: "India" },
      bio: "We're a pet-friendly workspace in Bangalore! Pawsitivity is part of our culture.",
      joinedAt: "2024-06-10",
      postCount: 3,
      petCount: 1,
      followers: 150,
      following: 12,
      petIds: []
    }
  ],
  pets: [
    {
      petId: "pet_001",
      ownerId: "user_001",
      ownerName: "Priya Sharma",
      name: "Max",
      type: "Dog",
      breed: "Golden Retriever",
      gender: "Male",
      age: { years: 3, months: 0 },
      birthDate: "2021-06-15",
      color: "Golden",
      weight: 32,
      photo: getImageUrl("pet_max"),
      specialNeeds: "None",
      activityLevel: 8,
      microchipId: "123456789",
      createdAt: "2024-09-15"
    },
    {
      petId: "pet_002",
      ownerId: "user_001",
      ownerName: "Priya Sharma",
      name: "Bella",
      type: "Dog",
      breed: "Golden Retriever",
      gender: "Female",
      age: { years: 2, months: 0 },
      birthDate: "2022-04-01",
      color: "Cream",
      weight: 28,
      photo: getImageUrl("pet_bella"),
      specialNeeds: "None",
      activityLevel: 9,
      microchipId: "987654321",
      createdAt: "2024-09-15"
    },
    {
      petId: "pet_003",
      ownerId: "user_002",
      ownerName: "Arjun Patel",
      name: "Simba",
      type: "Cat",
      breed: "Bengal",
      gender: "Male",
      age: { years: 4, months: 0 },
      birthDate: "2020-08-20",
      color: "Spotted Brown",
      weight: 6,
      photo: getImageUrl("pet_simba"),
      specialNeeds: "None",
      activityLevel: 7,
      microchipId: "112233445",
      createdAt: "2024-10-20"
    },
    {
      petId: "pet_004",
      ownerId: "user_003",
      ownerName: "Ananya Reddy",
      name: "Rocky",
      type: "Dog",
      breed: "Indian Pariah",
      gender: "Male",
      age: { years: 5, months: 0 },
      birthDate: "2019-01-01",
      color: "Brown",
      weight: 20,
      photo: getImageUrl("pet_rocky"),
      specialNeeds: "Rescued",
      activityLevel: 8,
      microchipId: "N/A",
      createdAt: "2023-05-11"
    },
     {
      petId: "pet_005",
      ownerId: "user_004",
      ownerName: "Rohan Mehta",
      name: "Bruno",
      type: "Dog",
      breed: "Beagle",
      gender: "Male",
      age: { years: 2, months: 6 },
      birthDate: "2022-07-10",
      color: "Tricolor",
      weight: 12,
      photo: getImageUrl("pet_bruno"),
      specialNeeds: "Loves food a bit too much.",
      activityLevel: 10,
      microchipId: "556677889",
      createdAt: "2024-01-02"
    },
    {
      petId: "pet_006",
      ownerId: "user_005",
      ownerName: "Ishita Gupta",
      name: "Leo",
      type: "Cat",
      breed: "Bengal",
      gender: "Male",
      age: { years: 1, months: 2 },
      birthDate: "2023-11-01",
      color: "Spotted Silver",
      weight: 5,
      photo: "https://picsum.photos/seed/leo/400/400",
      specialNeeds: "None",
      activityLevel: 9,
      microchipId: "121212121",
      createdAt: "2023-11-18"
    },
    {
      petId: "pet_007",
      ownerId: "user_005",
      ownerName: "Ishita Gupta",
      name: "Luna",
      type: "Cat",
      breed: "Bengal",
      gender: "Female",
      age: { years: 1, months: 2 },
      birthDate: "2023-11-01",
      color: "Spotted Brown",
      weight: 4,
      photo: "https://picsum.photos/seed/luna/400/400",
      specialNeeds: "None",
      activityLevel: 9,
      microchipId: "343434343",
      createdAt: "2023-11-18"
    },
    {
      petId: "pet_008",
      ownerId: "user_005",
      ownerName: "Ishita Gupta",
      name: "Milo",
      type: "Cat",
      breed: "Bengal",
      gender: "Male",
      age: { years: 1, months: 2 },
      birthDate: "2023-11-01",
      color: "Spotted Snow",
      weight: 5.5,
      photo: "https://picsum.photos/seed/milo/400/400",
      specialNeeds: "None",
      activityLevel: 9,
      microchipId: "565656565",
      createdAt: "2023-11-18"
    },
    {
      petId: "pet_009",
      ownerId: "user_006",
      ownerName: "Shreyan Bagchi",
      name: "Sheru",
      type: "Dog",
      breed: "Indie",
      gender: "Male",
      age: { years: 3, months: 0 },
      birthDate: "2021-09-01",
      color: "Fawn",
      weight: 18,
      photo: getImageUrl("pet_sheru"),
      specialNeeds: "None",
      activityLevel: 7,
      microchipId: "N/A",
      createdAt: "2024-08-01"
    },
    {
      petId: "pet_010",
      ownerId: "user_007",
      ownerName: "Ishaan Som Singh",
      name: "Mittens",
      type: "Cat",
      breed: "Persian",
      gender: "Female",
      age: { years: 2, months: 0 },
      birthDate: "2022-10-10",
      color: "White",
      weight: 4,
      photo: getImageUrl("pet_mittens"),
      specialNeeds: "Requires daily grooming.",
      activityLevel: 5,
      microchipId: "445566778",
      createdAt: "2024-07-22"
    }
  ],
  posts: [
    {
      postId: "post_001",
      userId: "user_001",
      userName: "Priya Sharma",
      userPhoto: getImageUrl("user_priya"),
      petId: "pet_001",
      petName: "Max",
      image: getImageUrl("post_golden_beach"),
      caption: "Morning walks at Juhu Beach with Max and Bella! They absolutely love the sand 🌊 #dogsofinstagram #mumbai",
      likes: 47,
      likedBy: ["user_004", "user_003"],
      comments: [
        { commentId: "cmt_001", userId: "user_004", userName: "Rohan Mehta", userPhoto: getImageUrl("user_rohan"), text: "Such cuties! Bruno would love to meet them 🐕", timestamp: "2025-01-15T08:30:00Z" },
        { commentId: "cmt_002", userId: "user_003", userName: "Ananya Reddy", userPhoto: getImageUrl("user_ananya"), text: "This is pure happiness!", timestamp: "2025-01-15T08:45:00Z" }
      ],
      saved: false,
      createdAt: subDays(now, 1).toISOString()
    },
    {
      postId: "post_002",
      userId: "user_002",
      userName: "Arjun Patel",
      userPhoto: getImageUrl("user_arjun"),
      petId: "pet_003",
      petName: "Simba",
      image: getImageUrl("post_simba_code"),
      caption: "Simba judging my code reviews from his favorite perch 😂 #catsofinstagram #coderlife",
      likes: 34,
      likedBy: ["user_005"],
      comments: [
         { commentId: "cmt_003", userId: "user_005", userName: "Ishita Gupta", userPhoto: getImageUrl("user_ishita"), text: "That's the look of a senior developer.", timestamp: "2025-01-15T09:10:00Z" }
      ],
      saved: true,
      createdAt: subDays(now, 2).toISOString()
    },
    {
      postId: "post_003",
      userId: "user_003",
      userName: "Ananya Reddy",
      userPhoto: getImageUrl("user_ananya"),
      petId: "pet_004",
      petName: "Rocky",
      image: getImageUrl("post_rocky_rescue"),
      caption: "4 years ago, I found Rocky on the streets. Today, he's my best friend ❤️ #AdoptDontShop #rescuedog",
      likes: 89,
      likedBy: ["user_001", "user_002", "user_004", "user_005"],
      comments: [],
      saved: false,
      createdAt: subDays(now, 3).toISOString()
    },
    {
      postId: "post_004",
      userId: "user_004",
      userName: "Rohan Mehta",
      userPhoto: getImageUrl("user_rohan"),
      petId: "pet_005",
      petName: "Bruno",
      image: getImageUrl("post_bruno_paratha"),
      caption: "Bruno stole an entire paratha from the table today. Living up to the Beagle reputation 😂 #beaglelife",
      likes: 56,
      likedBy: ["user_001"],
      comments: [],
      saved: false,
      createdAt: subDays(now, 4).toISOString()
    },
    {
      postId: "post_005",
      userId: "user_005",
      userName: "Ishita Gupta",
      userPhoto: getImageUrl("user_ishita"),
      image: getImageUrl("post_bengals_chaos"),
      caption: "Three bengals = chaos multiplied by infinity 😅 #bengalcat #catmom",
      likes: 42,
      likedBy: ["user_002"],
      comments: [],
      saved: false,
      createdAt: subDays(now, 5).toISOString()
    },
    {
      postId: "post_006",
      userId: "user_006",
      userName: "Shreyan Bagchi",
      userPhoto: getImageUrl("user_shreyan"),
      petId: "pet_009",
      petName: "Sheru",
      image: getImageUrl("post_sheru_cubbon"),
      caption: "Sunday morning vibes at Cubbon Park. Sheru loves the open space! #bangalorediaries #dogsofbangalore",
      likes: 28,
      likedBy: ["user_007", "user_008"],
      comments: [],
      saved: false,
      createdAt: subDays(now, 1).toISOString()
    },
    {
      postId: "post_007",
      userId: "user_007",
      userName: "Ishaan Som Singh",
      userPhoto: getImageUrl("user_ishaan"),
      petId: "pet_010",
      petName: "Mittens",
      image: getImageUrl("post_mittens_sunbathing"),
      caption: "The queen claims her throne (and the sunniest spot in the house). #persiancat #catlife",
      likes: 52,
      likedBy: ["user_006", "user_002"],
      comments: [],
      saved: true,
      createdAt: subDays(now, 2).toISOString()
    },
    {
      postId: "post_008",
      userId: "user_008",
      userName: "Grad Circle",
      userPhoto: getImageUrl("user_grad_circle"),
      petId: "pet_009",
      petName: "Sheru",
      image: getImageUrl("post_grad_circle_office"),
      caption: "We had a very good boy visit us at Grad Circle today! Sheru kept the team morale high. #petfriendlyoffice #bangalorestartups",
      likes: 95,
      likedBy: ["user_006", "user_007", "user_001"],
      comments: [],
      saved: false,
      createdAt: subDays(now, 6).toISOString()
    },
    {
      postId: "post_009",
      userId: "user_001",
      userName: "Priya Sharma",
      userPhoto: getImageUrl("user_priya"),
      petId: "pet_002",
      petName: "Bella",
      image: getImageUrl("post_bella_birthday"),
      caption: "Happy 2nd Birthday to my sweet Bella! 🎂 Can't believe how fast time flies. #birthdaygirl #dogbirthday",
      likes: 72,
      likedBy: ["user_002", "user_003", "user_004"],
      comments: [],
      saved: false,
      createdAt: subDays(now, 2).toISOString()
    },
    {
      postId: "post_010",
      userId: "user_001",
      userName: "Priya Sharma",
      userPhoto: getImageUrl("user_priya"),
      petId: "pet_001",
      petName: "Max",
      image: getImageUrl("post_max_muddy"),
      caption: "Someone had a little too much fun in the monsoon puddles today... Worth it for that smile! 🐾 #monsoon #muddydog",
      likes: 61,
      likedBy: ["user_005"],
      comments: [],
      saved: true,
      createdAt: subDays(now, 4).toISOString()
    }
  ],
  stories: [
    { storyId: "story_001", userId: "user_001", userName: "Priya", userPhoto: getImageUrl("user_priya"), storyImage: getImageUrl("story_max_playing"), caption: "Play time! #doglife", timestamp: subDays(now, 0).toISOString(), expiresAt: "2025-01-16T10:00:00Z" },
    { storyId: "story_002", userId: "user_002", userName: "Arjun", userPhoto: getImageUrl("user_arjun"), storyImage: getImageUrl("story_simba_nap"), caption: "Sleepy Sunday 😴 #catnap", timestamp: subDays(now, 0).toISOString(), expiresAt: "2025-01-16T09:00:00Z" },
    { storyId: "story_003", userId: "user_003", userName: "Ananya", userPhoto: getImageUrl("user_ananya"), storyImage: getImageUrl("story_rocky_park"), caption: "Park adventures! #rescuedog", timestamp: subDays(now, 0).toISOString(), expiresAt: "2025-01-16T11:00:00Z" },
    { storyId: "story_004", userId: "user_004", userName: "Rohan", userPhoto: getImageUrl("user_rohan"), storyImage: getImageUrl("story_bruno_zoomies"), caption: "Mid-day zoomies #beagle", timestamp: subDays(now, 0).toISOString(), expiresAt: "2025-01-16T08:00:00Z" },
    { storyId: "story_005", userId: "user_005", userName: "Ishita", userPhoto: getImageUrl("user_ishita"), storyImage: getImageUrl("story_cats_window"), caption: "Bird watching crew #catlife", timestamp: subDays(now, 0).toISOString(), expiresAt: "2025-01-16T12:00:00Z" },
  ],
  events: [
    {
      eventId: "event_001",
      organizerId: "user_008",
      organizerName: "Grad Circle",
      organizerPhoto: getImageUrl("user_grad_circle"),
      title: "Paws & Pints: Yappy Hour",
      description: "Join us for a fun evening of craft beer for humans and puppuccinos for dogs! A great chance to socialize and meet other pet lovers in the city.",
      bannerImage: getImageUrl("event_yappy_hour"),
      date: new Date(new Date().setDate(new Date().getDate() + 14)).toISOString(), // 2 weeks from now
      startTime: "17:00",
      endTime: "20:00",
      location: {
        venue: "Toit (Pet-Friendly Area)",
        city: "Bangalore",
        address: "298, 100 Feet Road, Namma Metro Pillar 62, Indiranagar",
        landmark: "Indiranagar"
      },
      petTypes: ['Dogs'],
      maxAttendees: 50,
      isFree: false,
      attendeeCount: 28,
      attendees: [],
      status: 'upcoming',
      createdAt: "2025-02-15T10:00:00Z"
    },
    {
      eventId: "event_002",
      organizerId: "user_003",
      organizerName: "Ananya Reddy",
      organizerPhoto: getImageUrl("user_ananya"),
      title: "Cubbon Park Indie Playdate",
      description: "A casual weekend meetup for all our lovely indie dogs and their parents at the Cubbon Park dog park. Let's celebrate our amazing desi hounds!",
      bannerImage: getImageUrl("event_indie_playdate"),
      date: new Date(new Date().setDate(new Date().getDate() + 21)).toISOString(), // 3 weeks from now
      startTime: "08:00",
      endTime: "10:00",
      location: {
        venue: "The Dog Park at Cubbon Park",
        city: "Bangalore",
        address: "Behind Cubbon Park Aquarium, Kasturba Road",
        landmark: "Cubbon Park"
      },
      petTypes: ['Dogs'],
      maxAttendees: null,
      isFree: true,
      attendeeCount: 16,
      attendees: [
        {
          userId: "user_001",
          userName: "Priya Sharma",
          userPhoto: getImageUrl("user_priya"),
          rsvpDate: "2025-02-18T10:00:00Z"
        }
      ],
      status: 'upcoming',
      createdAt: "2025-02-20T11:00:00Z"
    }
  ],
  forumTopics: [
    {
      topicId: "topic_001",
      categoryId: "dog-talk",
      userId: "user_001",
      userName: "Priya Sharma",
      userPhoto: getImageUrl("user_priya"),
      title: "Best dog-friendly cafes in Bangalore?",
      content: "Hey everyone! My husband and I are looking for some new spots to take Max and Bella on the weekends. We've been to TherPUP and Snoopy Paws Cafe, but would love to hear your recommendations!",
      views: 128,
      replyCount: 4,
      lastReplyAt: subDays(now, 1).toISOString(),
      createdAt: subDays(now, 3).toISOString(),
      replies: []
    },
    {
      topicId: "topic_002",
      categoryId: "cat-corner",
      userId: "user_002",
      userName: "Arjun Patel",
      userPhoto: getImageUrl("user_arjun"),
      title: "Tips for introducing a new cat to your home?",
      content: "I'm thinking of adopting another cat, but I'm worried about how Simba will react. He's been the only king of this castle for a while now. Any advice on making the introduction smooth?",
      views: 74,
      replyCount: 2,
      lastReplyAt: subDays(now, 2).toISOString(),
      createdAt: subDays(now, 5).toISOString(),
      replies: []
    },
    {
      topicId: "topic_003",
      categoryId: "health",
      userId: "user_004",
      userName: "Rohan Mehta",
      userPhoto: getImageUrl("user_rohan"),
      title: "Struggling with my Beagle's weight. Help!",
      content: "Bruno is a foodie and has put on a few extra kilos. The vet has advised us to get his weight under control. Any tips for managing a Beagle's diet without them staging a protest? 😂",
      views: 210,
      replyCount: 8,
      lastReplyAt: subDays(now, 0).toISOString(),
      createdAt: subDays(now, 2).toISOString(),
      replies: []
    },
    {
      topicId: "topic_004",
      categoryId: "all-pets",
      userId: "user_003",
      userName: "Ananya Reddy",
      userPhoto: getImageUrl("user_ananya"),
      title: "Question about pet adoption process in Hyderabad",
      content: "A friend of mine is looking to adopt a puppy in Hyderabad. Does anyone have recommendations for good shelters or rescue organizations to contact?",
      views: 55,
      replyCount: 1,
      lastReplyAt: subDays(now, 4).toISOString(),
      createdAt: subDays(now, 6).toISOString(),
      replies: []
    }
  ],
  lostPetAlerts: [
    {
      alertId: "lpa_001",
      status: 'active',
      ownerId: "user_006",
      ownerName: "Shreyan Bagchi",
      ownerPhone: "+91-9876543210",
      petId: "pet_011",
      petName: "Kaiser",
      petType: 'Dog',
      breed: "Siberian Husky",
      age: { years: 2, months: 0 },
      gender: 'Male',
      color: "Black and White",
      petPhoto: getImageUrl("pet_kaiser"),
      distinctiveMarks: "Blue eyes, one floppy ear.",
      lastSeenLocation: {
        address: "Koramangala 4th Block",
        city: "Bangalore",
        landmark: "Near Forum Mall"
      },
      lastSeenDate: "2025-02-20",
      lastSeenTime: "18:30",
      description: "Kaiser is very friendly but might be scared. He slipped out of his leash during our evening walk.",
      reward: 10000,
      createdAt: "2025-02-20T20:00:00Z",
    },
    {
      alertId: "lpa_002",
      status: 'found',
      ownerId: "user_007",
      ownerName: "Ishaan Som Singh",
      ownerPhone: "+91-9123456789",
      petId: "pet_012",
      petName: "Ginger",
      petType: 'Cat',
      breed: "Domestic Shorthair",
      age: { years: 1, months: 0 },
      gender: 'Male',
      color: "Orange Tabby",
      petPhoto: getImageUrl("pet_ginger"),
      distinctiveMarks: "Small nick on his left ear.",
      lastSeenLocation: {
        address: "Indiranagar 12th Main",
        city: "Bangalore",
        landmark: "Near 12th Main Park"
      },
      lastSeenDate: "2025-02-18",
      lastSeenTime: "22:00",
      description: "Ginger is an indoor cat and is not used to being outside. He is probably hiding somewhere nearby. He was found hiding under a car on the next street. Thanks to everyone who helped!",
      reward: 5000,
      createdAt: "2025-02-18T23:00:00Z",
    }
  ],
  tipArticles: [],
  conversations: [
    {
      conversationId: "convo_001",
      participants: ["user_001", "user_004"],
      lastMessage: "Sounds great! Let me know what time works for you.",
      lastMessageBy: "user_001",
      lastMessageAt: "2025-01-18T14:00:00Z",
      unreadCount: { "user_001": 0, "user_004": 2 },
      messages: [
        { messageId: "msg_001", senderId: "user_004", text: "Hey! Just saw you on the matchmaker. Bruno would love to meet Max. Would you be up for a playdate?", createdAt: "2025-01-18T13:55:00Z", readBy: ["user_001"] },
        { messageId: "msg_002", senderId: "user_001", text: "Hi Rohan! Yes, absolutely! Max would love that. He's very friendly.", createdAt: "2025-01-18T13:58:00Z", readBy: [] },
        { messageId: "msg_003", senderId: "user_001", text: "Sounds great! Let me know what time works for you.", createdAt: "2025-01-18T14:00:00Z", readBy: [] }
      ],
      createdAt: "2025-01-18T13:55:00Z"
    },
    {
      conversationId: "convo_002",
      participants: ["user_001", "user_003"],
      lastMessage: "He's doing great! So much energy.",
      lastMessageBy: "user_001",
      lastMessageAt: "2025-01-17T18:30:00Z",
      unreadCount: { "user_001": 0, "user_003": 0 },
      messages: [
        { messageId: "msg_004", senderId: "user_003", text: "Hi Priya! I saw your post about Rocky's adoption anniversary. So heartwarming. How is he doing?", createdAt: "2025-01-17T18:25:00Z", readBy: ["user_001"] },
        { messageId: "msg_005", senderId: "user_001", text: "He's doing great! So much energy.", createdAt: "2025-01-17T18:30:00Z", readBy: ["user_003"] }
      ],
      createdAt: "2025-01-17T18:25:00Z"
    },
    {
      conversationId: "convo_003",
      participants: ["user_001", "user_002"],
      lastMessage: "Haha, definitely! Let's connect next week.",
      lastMessageBy: "user_002",
      lastMessageAt: "2025-01-16T11:45:00Z",
      unreadCount: { "user_001": 1, "user_002": 0 },
      messages: [
        { messageId: "msg_006", senderId: "user_001", text: "That picture of Simba judging your code is hilarious!", createdAt: "2025-01-16T11:40:00Z", readBy: ["user_002"] },
        { messageId: "msg_007", senderId: "user_002", text: "I know right? He's the real boss around here. We should get our pets together sometime, though I'm not sure how Simba would feel about a dog!", createdAt: "2025-01-16T11:42:00Z", readBy: ["user_001"] },
        { messageId: "msg_008", senderId: "user_001", text: "We could try a slow introduction at a park maybe?", createdAt: "2025-01-16T11:43:00Z", readBy: ["user_002"] },
        { messageId: "msg_009", senderId: "user_002", text: "Haha, definitely! Let's connect next week.", createdAt: "2025-01-16T11:45:00Z", readBy: [] }
      ],
      createdAt: "2025-01-16T11:40:00Z"
    }
  ]
};
